# Generated by Django 4.1 on 2022-08-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_city_district_jobportal_city_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobportal',
            name='slug',
            field=models.SlugField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
