# Generated by Django 4.1 on 2022-08-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_jobportal_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPortal',
        ),
    ]
