# Generated by Django 4.1 on 2022-08-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_account_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
