# Generated by Django 4.1 on 2022-08-27 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_delete_jobportal'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discriptions', models.TextField(blank=True, max_length=200, null=True)),
                ('sub_mobile', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('payment', models.BooleanField(default=False)),
                ('count', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=30)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.categories')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.district')),
            ],
        ),
    ]
