# Generated by Django 4.1 on 2022-08-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobportal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobportal',
            name='count',
        ),
    ]
