# Generated by Django 4.1 on 2022-08-29 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_remove_jobportal_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobportal',
            name='slug',
        ),
    ]
