# Generated by Django 4.1 on 2022-08-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_remove_jobportal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobportal',
            name='slug',
            field=models.SlugField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
