# Generated by Django 4.1 on 2022-08-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_jobportal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobportal',
            name='ordernumber',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
