# Generated by Django 4.1 on 2022-09-04 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0007_jobportal_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobportal',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobportal',
            name='booked_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
