# Generated by Django 4.1 on 2022-09-05 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_alter_account_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discriptions', models.TextField(blank=True, max_length=300, null=True)),
                ('sub_mobile', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=20)),
                ('payment', models.BooleanField(default=False)),
                ('rate', models.IntegerField()),
                ('available', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=30)),
                ('ordernumber', models.CharField(max_length=40)),
                ('booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_at', models.CharField(max_length=40)),
                ('booked_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_persons', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.categories')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.district')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
