# Generated by Django 4.1 on 2022-09-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0002_alter_job_detail_valid_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('job_start', models.BooleanField(default=False)),
                ('start_otp', models.BooleanField(default=False)),
                ('start_verify', models.BooleanField(default=False)),
                ('job_end', models.BooleanField(default=False)),
                ('end_otp', models.BooleanField(default=False)),
                ('end_verify', models.BooleanField(default=False)),
            ],
        ),
    ]
