# Generated by Django 4.1 on 2022-09-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_jobverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobverification',
            name='order_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
