# Generated by Django 4.1 on 2022-09-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0005_jobverification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_detail',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
