# Generated by Django 4.1 on 2022-09-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentportal', '0003_rent_detail_price_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_detail',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
