# Generated by Django 4.1 on 2022-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentportal', '0004_alter_rent_detail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_detail',
            name='price_in',
            field=models.CharField(choices=[('per_hour', 'per_hour'), ('per_day', 'per_day')], default='per_day', max_length=100),
        ),
        migrations.AlterField(
            model_name='rent_detail',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rent_detail',
            name='valid_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
