# Generated by Django 4.1 on 2022-09-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentportal', '0005_alter_rent_detail_price_in_alter_rent_detail_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_detail',
            name='image',
            field=models.ImageField(upload_to='rent'),
        ),
        migrations.AlterField(
            model_name='rent_detail',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='rent'),
        ),
        migrations.AlterField(
            model_name='rent_detail',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rent'),
        ),
    ]
