# Generated by Django 4.1 on 2022-09-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentportal', '0006_alter_rent_detail_image_alter_rent_detail_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_detail',
            name='valid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
