# Generated by Django 4.1 on 2022-09-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentportal', '0007_alter_rent_detail_valid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_detail',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
