# Generated by Django 4.1 on 2022-09-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentportal', '0009_remove_rent_detail_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent_detail',
            old_name='returned',
            new_name='returned_it',
        ),
        migrations.AddField(
            model_name='rent_detail',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
