# Generated by Django 4.1 on 2022-09-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentportal', '0010_rename_returned_rent_detail_returned_it_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_detail',
            name='item_backed',
            field=models.BooleanField(default=False),
        ),
    ]
