# Generated by Django 4.1 on 2022-09-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentportal', '0011_rent_detail_item_backed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent_detail',
            name='returned_it',
        ),
    ]
