# Generated by Django 4.1 on 2022-09-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentportal', '0015_rentcomplaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentcomplaint',
            old_name='job',
            new_name='rent',
        ),
    ]
